name: Display Input Parameter

on: 
  workflow_dispatch:
    inputs:
      custom_message:
        description: 'Enter a custom message'
        required: true
        default: 'Hello, GitHub Actions!'

jobs:
  display-input:
    runs-on: ubuntu-latest
    steps:
    - name: Display the input message
      run: echo "You entered: ${{ github.event.inputs.custom_message }}"
