name: Display Input Parameter

on: 
  workflow_dispatch:
    inputs:
      custom_message:
        description: 'Enter a custom message'
        required: true
        default: 'Hello, GitHub Actions!'

jobs:
  display-input:
    runs-on: ubuntu-latest
    steps:
    - name: Set input message to the environment variable
      run: echo "MESSAGE=${{ github.event.inputs.custom_message }}" >> $GITHUB_ENV

    - name: Display the input message
      run: echo "You entered: $MESSAGE"
